# Generated by Django 5.1.6 on 2025-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(db_index=True, max_length=20)),
                ('video_title', models.CharField(blank=True, max_length=500)),
                ('summary_type', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('tldr', 'TLDR'), ('key_points', 'Key Points')], default='concise', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Video Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
